/*7.1 Inner Join*/
SELECT FIRSTNAME, LASTNAME, INVOICEID 
FROM CUSTOMER INNER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

/*7.2 Outer Join*/
SELECT CUSTOMER.CUSTOMERID, FIRSTNAME, LASTNAME, INVOICE.INVOICEID, TOTAL
FROM CUSTOMER FULL OUTER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

/*7.3 Right Join*/
SELECT NAME, TITLE FROM ALBUM RIGHT OUTER JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID;

/*7.4 Cross Join*/
SELECT NAME, ALBUM.ARTISTID, ALBUMID, TITLE  FROM ALBUM CROSS JOIN ARTIST ORDER BY NAME ASC;

/*7.5 Self Join*/
select e1.EMPLOYEEID, e1.LASTNAME, e1.FIRSTNAME, e1.TITLE, e1.BIRTHDATE, e1.HIREDATE, e1.EMAIL EMAIL,
e2.FIRSTNAME as SUPERVISORFIRSTNAME, e2.LASTNAME as SUPERVISORLASTNAME
from EMPLOYEE e1 left outer join EMPLOYEE e2 on e1.REPORTSTO = e2.EMPLOYEEID;