/*2.1 Select*/
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';
SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

/*2.2 Order By*/
SELECT * FROM ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CUSTOMER ORDER BY CITY ASC;

/*2.3 Insert Into*/
INSERT INTO GENRE VALUES (26,'Podcast');
INSERT INTO GENRE VALUES (27,'Historic');

INSERT INTO EMPLOYEE VALUES (9,'Deer','John','Unspecified', NULL, DATE '2099-01-01','2001-04-04',
    'Somewhere','Maybe','Whoknows','Idont',00000,0000000000,0000000000,'noone@nothing.com');
INSERT INTO EMPLOYEE VALUES (10,'Doe','Jane','Unspecified', NULL, DATE '2099-01-02','2001-04-04',
    'Somewhere','Maybe','Whoknows','Idont',00000,0000000000,0000000000,'nobody@nothing.com');

INSERT INTO CUSTOMER VALUES (60, 'Alph A.', 'Bett', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'abc@efg.com', NULL);
INSERT INTO CUSTOMER VALUES (61, 'Seggy', 'Fault', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'null@pointer.com', NULL);

/*2.4 Update*/
UPDATE CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME = 'Walter' WHERE (FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchel');
UPDATE ARTIST SET NAME = 'CCR' WHERE NAME = 'Creedence Clearwater Revival';

/*2.5 LIKE*/
SELECT * FROM INVOICE WHERE BILLINGADDRESS LIKE 'T%';

/*2.6 BETWEEN*/
SELECT * FROM INVOICE WHERE TOTAL BETWEEN 15 AND 50;
SELECT * FROM EMPLOYEE WHERE HIREDATE BETWEEN DATE '2003-06-01' AND DATE '2004-03-01';

/*2.7 DELETE*/
ALTER TABLE INVOICE
DROP CONSTRAINT FK_INVOICECUSTOMERID;
ALTER TABLE INVOICE
ADD CONSTRAINT FK_INVOICECUSTOMERID_CASCADE
   FOREIGN KEY (INVOICEID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE;
   
ALTER TABLE INVOICELINE
DROP CONSTRAINT FK_INVOICELINEINVOICEID;
ALTER TABLE INVOICE
ADD CONSTRAINT FK_INVOICELINEINVOICEID_CASCADE
   FOREIGN KEY (INVOICELINEID) REFERENCES INVOICE(INVOICEID) ON DELETE CASCADE;
   
DELETE FROM CUSTOMER WHERE (FIRSTNAME = 'Robert' AND LASTNAME = 'Walker');
