-- conn sys as sysdba

-- USER name IDENTIFIED BY password;
CREATE USER demo IDENTIFIED BY demo;

GRANT CREATE SESSION TO demo;

GRANT CREATE ANY TABLE TO demo;

GRANT RESOURCE TO demo;

GRANT SELECT_CATALOG_ROLE TO demo;

GRANT CREATE ANY VIEW TO demo;

GRANT UNLIMITED TABLESPACE TO demo;
